/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/my_scene.glb --transform --simplify 
Files: public/my_scene.glb [213.81MB] > /Users/vale/Desktop/💻 Dev/SwellPoem.github.io/my_scene-transformed.glb [6.52MB] (97%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/my_scene2.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="room" position={[-0.105, 0.354, 0.521]}>
          <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials.PaletteMaterial002} />
        </group>
        <mesh name="mouse" geometry={nodes.mouse.geometry} material={materials.PaletteMaterial001} position={[-0.308, 1.765, -1.526]} />
        <mesh name="desk_lamp" geometry={nodes.desk_lamp.geometry} material={materials.PaletteMaterial003} position={[0.216, 2.814, -1.539]} />
        <group name="chair" position={[-1.087, 1.23, -0.738]} rotation={[0, -0.199, 0]}>
          <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube003_1" geometry={nodes.Cube003_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube003_2" geometry={nodes.Cube003_2.geometry} material={materials.PaletteMaterial001} />
        </group>
        <group name="book5" position={[1.849, 1.41, -2.388]}>
          <mesh name="Cube053" geometry={nodes.Cube053.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube053_1" geometry={nodes.Cube053_1.geometry} material={materials.PaletteMaterial001} />
        </group>
        <group name="drawer" position={[2.128, 0.733, -2.96]}>
          <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube013_1" geometry={nodes.Cube013_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube013_2" geometry={nodes.Cube013_2.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube013_3" geometry={nodes.Cube013_3.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube013_4" geometry={nodes.Cube013_4.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube013_5" geometry={nodes.Cube013_5.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube013_6" geometry={nodes.Cube013_6.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube013_7" geometry={nodes.Cube013_7.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube013_8" geometry={nodes.Cube013_8.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube013_9" geometry={nodes.Cube013_9.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube013_10" geometry={nodes.Cube013_10.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube013_11" geometry={nodes.Cube013_11.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube013_12" geometry={nodes.Cube013_12.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube013_13" geometry={nodes.Cube013_13.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube013_14" geometry={nodes.Cube013_14.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube013_15" geometry={nodes.Cube013_15.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube013_16" geometry={nodes.Cube013_16.geometry} material={materials.PaletteMaterial001} />
        </group>
        <group name="room-entry" position={[-0.105, 0.311, 1.221]} rotation={[0, 0, -Math.PI]} scale={[-1, -0.669, -1]}>
          <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube014_1" geometry={nodes.Cube014_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube014_2" geometry={nodes.Cube014_2.geometry} material={materials.PaletteMaterial002} />
          <mesh name="Cube014_3" geometry={nodes.Cube014_3.geometry} material={materials.PaletteMaterial001} />
        </group>
        <mesh name="cat" geometry={nodes.cat.geometry} material={materials.PaletteMaterial004} position={[-0.432, 0.985, 3.25]} rotation={[Math.PI / 2, 0, -0.622]} scale={0.008} />
        <group name="Head" position={[0.732, 2.171, -1.376]} rotation={[1.624, -0.03, -0.139]} scale={0.129}>
          <mesh name="Head_1" geometry={nodes.Head_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Head_2" geometry={nodes.Head_2.geometry} material={materials.PaletteMaterial004} />
        </group>
        <mesh name="LowerArm2" geometry={nodes.LowerArm2.geometry} material={materials.PaletteMaterial001} position={[0.917, 2.105, -1.377]} rotation={[-1.547, -0.944, 1.453]} scale={0.129} />
        <mesh name="Link1" geometry={nodes.Link1.geometry} material={materials.PaletteMaterial001} position={[-0.897, 2.178, 3.239]} rotation={[Math.PI / 2, 0, 2.548]} scale={0.016}>
          <mesh name="Link2" geometry={nodes.Link2.geometry} material={materials.PaletteMaterial001} position={[0.9, -0.198, -11.407]} rotation={[0.638, 0.401, -0.104]}>
            <mesh name="Link3" geometry={nodes.Link3.geometry} material={materials.PaletteMaterial001} position={[5.209, -7.923, -17.812]} rotation={[-0.403, -0.237, -0.107]}>
              <mesh name="end_eff" geometry={nodes.end_eff.geometry} material={materials.PaletteMaterial001} position={[-20.224, 29.311, 18.019]} rotation={[-0.69, -0.482, -0.095]} />
            </mesh>
          </mesh>
        </mesh>
        <group name="Swim_Goggles_Cap" position={[0.788, 1.127, 3.313]} rotation={[3.13, -0.497, 3.1]} scale={0.022}>
          <mesh name="10538_Swim_Goggles_v1_L3" geometry={nodes['10538_Swim_Goggles_v1_L3'].geometry} material={materials.PaletteMaterial005} />
          <mesh name="10538_Swim_Goggles_v1_L3_1" geometry={nodes['10538_Swim_Goggles_v1_L3_1'].geometry} material={materials.PaletteMaterial006} />
        </group>
        <mesh name="aboutMe" geometry={nodes.aboutMe.geometry} material={materials.PaletteMaterial001} position={[1.491, 1.228, 3.211]} rotation={[Math.PI / 2, 0, -0.781]} />
      </group>
    </group>
  )
}

useGLTF.preload('/my_scene2.glb')
